sonar.projectKey=kotovann_hotels-webapp
sonar.organization=hotels-webapp
sonar.sources=backend/app,backend/config,backend/utils,frontend/src
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.sourceEncoding=UTF-8