# Generated by Django 6.0.4 on 2026-04-17 14:04

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
            ],
            options={
                'verbose_name': 'Группа пользователей',
                'verbose_name_plural': 'Группы пользователей',
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='primary_group',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'Введен некорректный email.'}, help_text='Обязательное поле, должно быть уникальным.', max_length=100, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.CreateModel(
            name='GroupPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.SmallIntegerField(verbose_name='Приоритет группы')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_priority', to='auth.group', verbose_name='Группа пользователей')),
            ],
            options={
                'verbose_name': 'Приоритет группы пользователей',
                'verbose_name_plural': 'Приоритеты групп пользователей',
                'ordering': ['-priority'],
            },
        ),
    ]
