# Generated by Django 6.0.4 on 2026-05-04 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='is_owner',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
