# Generated by Django 6.0.4 on 2026-04-10 18:34

import app.hotels.models
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название отеля')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(error_messages={'invalid': 'Введен некорректный номер телефона'}, max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(error_messages={'invalid': 'Введен некорректный email'}, max_length=100, unique=True, verbose_name='Email-адрес')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
                'db_table': 'hotel',
                'ordering': ['is_active', 'country', 'city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название типа')),
                ('description', models.TextField(verbose_name='Описание')),
                ('size', models.PositiveSmallIntegerField(help_text='в квадратных метрах', validators=[django.core.validators.MinValueValidator(2, message='Номер должен быть размером хотя бы 2 кв. м.')], verbose_name='Площадь')),
                ('capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Номер должен вмещать хотя бы одного человека')], verbose_name='Вместимость')),
                ('bedroom_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Номер должен иметь хотя бы одно спальное место')], verbose_name='Количество спален')),
                ('bathroom_count', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Количество ванных не может быть меньше нуля')], verbose_name='Количество ванных комнат')),
                ('has_balcony', models.BooleanField(default=False, verbose_name='Есть балкон')),
            ],
            options={
                'verbose_name': 'Тип номера',
                'verbose_name_plural': 'Типы номеров',
                'db_table': 'room_type',
                'ordering': ['name', '-capacity', '-size'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pets_allowed', models.BooleanField(default=False, verbose_name='Можно с животными')),
                ('is_smoking_allowed', models.BooleanField(default=False, verbose_name='Можно курить')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Цена не может быть меньше нуля')], verbose_name='Цена за ночь')),
                ('extra_pay_per_person', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Цена не может быть меньше нуля')], verbose_name='Доплата за дополнительного человека')),
                ('floor', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Этаж не может быть меньше 1'), django.core.validators.MaxValueValidator(100, message='Этаж не может быть больше 100')], verbose_name='Номер этажа')),
                ('number_on_floor', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальный порядковый номер комнаты равен 1'), django.core.validators.MaxValueValidator(99, message='Максимальный порядковый номер комнаты равен 99')], verbose_name='Порядковый номер на этаже')),
                ('variant', models.CharField(blank=True, help_text='Например, 1A и 1B (указать только букву)', max_length=1, null=True, validators=[django.core.validators.RegexValidator(message='Вариация может быть только латинской буквой в высшем регистре', regex='^[A-Z]$')], verbose_name='Вариация номера')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.roomtype')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'db_table': 'room',
                'ordering': ['hotel__name', 'room_type__name', 'floor', 'number_on_floor', 'variant', '-price_per_night'],
            },
        ),
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_path', models.ImageField(upload_to=app.hotels.models._photo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'], message='Формат файла не поддерживается')], verbose_name='Путь к фото')),
                ('sort_order_number', models.PositiveSmallIntegerField(verbose_name='Порядковый номер')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='hotels.room')),
            ],
            options={
                'verbose_name': 'Фото номера',
                'verbose_name_plural': 'Фото номеров',
                'db_table': 'room_photo',
                'ordering': ['room__hotel__name', 'room__floor', 'room__number_on_floor', 'room__variant', 'sort_order_number'],
                'constraints': [models.UniqueConstraint(fields=('room', 'sort_order_number'), name='unique_order_number_per_room', violation_error_message='Уже существует фото комнаты с таким порядковым номером')],
            },
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('hotel', 'floor'), name='unique_floor_per_hotel', violation_error_message='В отеле этаж с таких номером может быть только один'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('hotel', 'floor', 'number_on_floor', 'variant'), name='unique_room_per_hotel', violation_error_message='В отеле может быть только одна комнатас таким номером и вариантом на этаже'),
        ),
    ]
