# Generated by Django 6.0.4 on 2026-04-11 08:40

import app.hotels.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomphoto',
            name='photo_path',
            field=models.ImageField(upload_to=app.hotels.models._photo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'], message='Формат файла не поддерживается')], verbose_name='Фото'),
        ),
    ]
