# Generated by Django 6.0.4 on 2026-04-20 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_roomphoto_photo_path'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='room',
            name='unique_floor_per_hotel',
        ),
        migrations.RenameField(
            model_name='roomphoto',
            old_name='photo_path',
            new_name='photo',
        ),
    ]
