# Generated by Django 6.0.4 on 2026-04-20 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_remove_room_unique_floor_per_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='size',
            field=models.PositiveSmallIntegerField(help_text='в квадратных метрах', validators=[django.core.validators.MinValueValidator(2, message='Номер должен быть размером хотя бы 2 кв. м.')], verbose_name='Площадь (кв.м.)'),
        ),
    ]
