# Generated by Django 6.0.4 on 2026-04-20 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_alter_roomtype_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Этаж не может быть меньше 1'), django.core.validators.MaxValueValidator(10, message='Этаж не может быть больше 100')], verbose_name='Номер этажа'),
        ),
    ]
