# Generated by Django 6.0.4 on 2026-04-20 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_alter_room_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='floor_count',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1, message='Количество этажей не может быть меньше 1'), django.core.validators.MaxValueValidator(10, message='Количество этажей не может быть больше 10')], verbose_name='Количество этажей'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Этаж не может быть меньше 1'), django.core.validators.MaxValueValidator(10, message='Этаж не может быть больше 10')], verbose_name='Номер этажа'),
        ),
    ]
