# Generated by Django 6.0.4 on 2026-04-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_hotel_floor_count_alter_room_floor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['floor', 'number_on_floor', 'variant'], 'verbose_name': 'Номер', 'verbose_name_plural': 'Номера'},
        ),
    ]
