# Generated by Django 6.0.4 on 2026-04-29 12:45

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_alter_room_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('SU', 'Сюит'), ('A', 'Апартамент'), ('L', 'Люкс'), ('JSU', 'Джуниор сюит'), ('ST', 'Студия'), ('1', 'Первая категория (стандарт)'), ('2', 'Вторая категория'), ('3', 'Третья категория'), ('4', 'Четвёртая категория'), ('5', 'Пятая категория')], max_length=3, unique=True, verbose_name='Категория')),
                ('min_area', models.PositiveSmallIntegerField(verbose_name='Минимальная площадь (кв.м.)')),
                ('requires_kitchen', models.BooleanField(default=False, verbose_name='Требуется кухонное оборудование')),
                ('required_bathroom_type', models.CharField(choices=[('S', 'Общий'), ('P', 'Частичный (без ванны/душа)'), ('F', 'Полный санузел')], default='F', max_length=1, verbose_name='Необходимый тип санузла')),
                ('min_rooms', models.PositiveSmallIntegerField(default=1, verbose_name='Минимальное количество комнат')),
            ],
            options={
                'verbose_name': 'Категория номера',
                'verbose_name_plural': 'Категории номеров',
                'db_table': 'room_category',
                'ordering': ['tier'],
            },
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['country', 'city', 'name', '-is_active'], 'verbose_name': 'Отель', 'verbose_name_plural': 'Отели'},
        ),
        migrations.AlterModelOptions(
            name='roomphoto',
            options={'ordering': ['room__hotel__name', 'room__floor', 'room__number_on_floor', 'room__variant', 'order_number'], 'verbose_name': 'Фото номера', 'verbose_name_plural': 'Фото номеров'},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ['name', '-standard_capacity', '-size'], 'verbose_name': 'Тип номера', 'verbose_name_plural': 'Типы номеров'},
        ),
        migrations.RemoveConstraint(
            model_name='roomphoto',
            name='unique_order_number_per_room',
        ),
        migrations.RenameField(
            model_name='roomphoto',
            old_name='sort_order_number',
            new_name='order_number',
        ),
        migrations.RenameField(
            model_name='roomtype',
            old_name='capacity',
            new_name='standard_capacity',
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_in_time',
            field=models.TimeField(default=datetime.time(14, 0), verbose_name='Время заезда'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_out_time',
            field=models.TimeField(default=datetime.time(12, 0), verbose_name='Время выезда (расчётный час)'),
        ),
        migrations.AddField(
            model_name='room',
            name='bed_count',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Номер должен иметь хотя бы одно спальное место')], verbose_name='Количество спальных мест'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='bathroom_type',
            field=models.CharField(choices=[('S', 'Общий'), ('P', 'Частичный (без ванны/душа)'), ('F', 'Полный санузел')], default='F', max_length=1, verbose_name='Тип санузла'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='has_kitchen',
            field=models.BooleanField(default=False, verbose_name='Есть кухня'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='living_room_count',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0, message='Количество гостинных не может быть меньше нуля')], verbose_name='Количество гостинных'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='bedroom_count',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Номер должен иметь хотя бы одну спальню')], verbose_name='Количество спален'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='size',
            field=models.PositiveSmallIntegerField(help_text='в квадратных метрах', validators=[django.core.validators.MinValueValidator(2, message='Номер должен быть размером хотя бы 2 кв.м.')], verbose_name='Площадь (кв.м.)'),
        ),
        migrations.AlterConstraint(
            model_name='room',
            name='unique_room_per_hotel',
            constraint=models.UniqueConstraint(fields=('hotel', 'floor', 'number_on_floor', 'variant'), name='unique_room_per_hotel', violation_error_message='В отеле может быть только одна комната с таким номером и вариантом на этаже'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='room_types', to='hotels.roomcategory', verbose_name='Категория по классификации'),
            preserve_default=False,
        ),
    ]
