# Generated by Django 6.0.4 on 2026-05-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_roomcategory_alter_hotel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomphoto',
            name='photo',
        ),
        migrations.AddField(
            model_name='roomphoto',
            name='photo_url',
            field=models.URLField(default='', verbose_name='Фото URL'),
            preserve_default=False,
        ),
    ]
