# Generated by Django 6.0.4 on 2026-04-10 18:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='В брони должен быть хотя бы один взрослый')], verbose_name='Количество взрослых')),
                ('children_count', models.PositiveSmallIntegerField(verbose_name='Количество детей')),
                ('pets_count', models.PositiveSmallIntegerField(verbose_name='Количество животных')),
                ('check_in_date', models.DateField(verbose_name='Дата въезда')),
                ('check_out_date', models.DateField(verbose_name='Дата выселения')),
                ('status', models.CharField(choices=[('Активно', 'Active'), ('Перенесено', 'Moved'), ('Отменено', 'Cancelled'), ('Завершено', 'Closed')], default='Активно', verbose_name='Статус брони')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='К оплате')),
                ('payment_status', models.CharField(choices=[('Не оплачено', 'Not Payed'), ('Оплачено', 'Payed')], default='Не оплачено', verbose_name='Статус платежа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены')),
                ('cancellation_reason', models.CharField(max_length=255, verbose_name='Причина отмены')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotels.room', verbose_name='Номер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Зарегистрированный пользователь')),
            ],
            options={
                'db_table': 'booking',
                'ordering': ['-created_at', 'room__hotel__name', 'room__floor', 'room__number_on_floor', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальная оценка 1 звезда'), django.core.validators.MaxValueValidator(5, message='Максимальная оценка 5 звезд')], verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, max_length=3072, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking', verbose_name='Запись о бронировании')),
            ],
            options={
                'db_table': 'review',
                'ordering': ['is_published', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('check_out_date__gt', models.F('check_in_date'))), name='booking_checkout_after_checkin', violation_error_message='Дата выезда должна быть позже даты заезда'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', False), ('status', 'Отменено')), ('status__in', ['Активно', 'Завершено', 'Перенесено']), _connector='OR'), name='booking_cancelled_at_required', violation_error_message='При отмене брони необходимо указать дату отмены'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_published', True), ('published_at__isnull', False)), ('is_published', False), _connector='OR'), name='review_published_at_required', violation_error_message='При публикации необходимо указать дату публикации'),
        ),
    ]
