# Generated by Django 6.0.4 on 2026-04-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at', 'room__hotel__name', 'room__floor', 'room__number_on_floor', 'user__last_name'], 'verbose_name': 'Бронь', 'verbose_name_plural': 'Брони'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['is_published', '-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Будет расчитана после добавления записи о брони', max_digits=10, verbose_name='К оплате'),
        ),
    ]
