# Generated by Django 6.0.4 on 2026-04-22 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_options_alter_review_options_and_more'),
        ('hotels', '0007_alter_room_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at', 'status'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_cancelled_at_required',
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='review_published_at_required',
        ),
        migrations.AddField(
            model_name='review',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Причина отказа'),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликован'), ('moderation', 'Ожидает проверки'), ('rejected', 'Не прошел модерацию'), ('deleted', 'Удален')], default='moderation', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Причина отмены'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateTimeField(verbose_name='Дата въезда'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_date',
            field=models.DateTimeField(verbose_name='Дата выселения'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('open', 'Не оплачено'), ('closed', 'Оплачено')], default='open', verbose_name='Статус платежа'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('moved', 'Перенесено'), ('cancelled', 'Отменено'), ('closed', 'Завершено')], default='active', verbose_name='Статус брони'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancellation_reason__isnull', False), ('cancelled_at__isnull', False), ('status', 'cancelled')), models.Q(('status', 'cancelled'), _negated=True), _connector='OR'), name='booking_cancelled_at_required', violation_error_message='При отмене брони необходимо указать дату отмены и причину'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', False), ('status', 'published')), models.Q(('status', 'published'), _negated=True), _connector='OR'), name='review_published_at_required', violation_error_message='При публикации необходимо указать дату публикации'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('moderated_by__isnull', False), ('status__in', ['published', 'rejected'])), ('status__in', ['moderation', 'deleted']), _connector='OR'), name='review_moderated_by_required', violation_error_message='После прохождения модерации должен быть сохранен модератор'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rejection_reason__isnull', False), ('status', 'rejected')), models.Q(models.Q(('status', 'rejected'), _negated=True)), _connector='OR'), name='review_rejection_reason_required', violation_error_message='После отказа в публикации должна быть указана причина'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_published',
        ),
    ]
