# Generated by Django 6.0.4 on 2026-04-22 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_review_options_and_more'),
        ('hotels', '0007_alter_room_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_cancelled_at_required',
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='review_published_at_required',
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='review_moderated_by_required',
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='review_rejection_reason_required',
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('O', 'Не оплачено'), ('C', 'Оплачено')], default='O', verbose_name='Статус платежа'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('A', 'Активно'), ('M', 'Перенесено'), ('CA', 'Отменено'), ('CL', 'Завершено')], default='A', verbose_name='Статус брони'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('P', 'Опубликован'), ('M', 'Ожидает проверки'), ('R', 'Не прошел модерацию'), ('D', 'Удален')], default='M', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancellation_reason__isnull', False), ('cancelled_at__isnull', False), ('status', 'CA')), models.Q(('status', 'CA'), _negated=True), _connector='OR'), name='booking_cancelled_at_required', violation_error_message='При отмене брони необходимо указать дату отмены и причину'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', False), ('status', 'P')), models.Q(('status', 'P'), _negated=True), _connector='OR'), name='review_published_at_required', violation_error_message='При публикации необходимо указать дату публикации'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('moderated_by__isnull', False), ('status__in', ['P', 'R'])), ('status__in', ['M', 'D']), _connector='OR'), name='review_moderated_by_required', violation_error_message='После прохождения модерации должен быть сохранен модератор'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rejection_reason__isnull', False), ('status', 'R')), models.Q(models.Q(('status', 'R'), _negated=True)), _connector='OR'), name='review_rejection_reason_required', violation_error_message='После отказа в публикации должна быть указана причина'),
        ),
    ]
