# Generated by Django 6.0.4 on 2026-04-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_booking_cancelled_at_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Будет расчитана после добавления записи о брони', max_digits=10, verbose_name='К оплате'),
        ),
    ]
