# Generated by Django 6.0.4 on 2026-04-29 12:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_total_price'),
        ('hotels', '0009_seed_room_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('O', 'Ждет оплаты'), ('I', 'Не актуально'), ('E', 'Просрочен'), ('C', 'Оплачено')], default='O', max_length=1, verbose_name='Статус платежа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='К оплате')),
                ('purpose', models.CharField(choices=[('PP', 'Предоплата'), ('FP', 'Полная оплата бронирования'), ('EP', 'Доплата'), ('RF', 'Возврат'), ('PN', 'Штраф')], default='PP', max_length=3, verbose_name='Назначение платежа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'db_table': 'booking_payment',
                'ordering': ['-created_at', '-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='CancelledBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отмены')),
                ('cancellation_reason', models.CharField(max_length=255, verbose_name='Причина отмены')),
            ],
            options={
                'verbose_name': 'Отменненное бронирование',
                'verbose_name_plural': 'Отмененные бронирования',
                'db_table': 'cancelled_booking',
                'ordering': ['-cancelled_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at', 'room__hotel__name', 'room__floor', 'room__number_on_floor', 'user__last_name'], 'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_checkout_after_checkin',
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_cancelled_at_required',
        ),
        migrations.AddField(
            model_name='booking',
            name='moved_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moved_from', to='bookings.booking', verbose_name='Новое бронирование (при переносе)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='type',
            field=models.CharField(choices=[('G', 'Гарантированное'), ('N', 'Негарантированное')], default='G', help_text='С предоплатой или без (гарантированное/негарантированное)', max_length=2, verbose_name='Тип бронирования'),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(verbose_name='Дата въезда'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_date',
            field=models.DateField(verbose_name='Дата выселения'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='children_count',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Количество детей не может быть меньше нуля')], verbose_name='Количество детей'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pets_count',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Количество питомцев не может быть меньше нуля')], verbose_name='Количество питомцев'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('A', 'Активно'), ('M', 'Перенесено'), ('CA', 'Отменено'), ('CL', 'Завершено')], default='A', max_length=2, verbose_name='Статус бронирования'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('P', 'Опубликован'), ('M', 'Ожидает проверки'), ('R', 'Не прошел модерацию'), ('D', 'Удален')], default='M', max_length=1),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('check_out_date__gt', models.F('check_in_date'))), name='booking_check_out_after_check_in', violation_error_message='Дата выезда должна быть позже даты заезда'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('moved_to__isnull', False), ('status', 'M')), models.Q(('status', 'M'), _negated=True), _connector='OR'), name='booking_moved_to_required', violation_error_message='При переносе бронирования необходимо указать ссылку на новое'),
        ),
        migrations.AlterConstraint(
            model_name='review',
            name='review_published_at_required',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', False), ('status', 'P')), models.Q(('status', 'P'), _negated=True), _connector='OR'), name='review_published_at_required', violation_error_message='Необходимо указать дату публикации'),
        ),
        migrations.AlterConstraint(
            model_name='review',
            name='review_moderated_by_required',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('moderated_by__isnull', False), ('status__in', ['P', 'R'])), ('status__in', ['M', 'D']), _connector='OR'), name='review_moderated_by_required', violation_error_message='Необходимо указать модератора'),
        ),
        migrations.AlterConstraint(
            model_name='review',
            name='review_rejection_reason_required',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rejection_reason__isnull', False), ('status', 'R')), models.Q(models.Q(('status', 'R'), _negated=True)), _connector='OR'), name='review_rejection_reason_required', violation_error_message='Необходимо указать причину отказа'),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking', verbose_name='Бронирование'),
        ),
        migrations.AddField(
            model_name='cancelledbooking',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='bookings.booking', verbose_name='Бронирование'),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
    ]
