# Generated by Django 6.0.4 on 2026-05-01 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_guest'),
        ('bookings', '0006_bookingpayment_cancelledbooking_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at', 'room__hotel__name', 'room__floor', 'room__number_on_floor', 'guest__user__last_name'], 'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='review_moderated_by_required',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.guest', verbose_name='Гость'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to='accounts.moderator', verbose_name='Модератор'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('P', 'Опубликован'), ('D', 'Черновик'), ('M', 'Ожидает проверки'), ('R', 'Не прошел модерацию'), ('A', 'Убран из публичного доступа')], default='M', max_length=1),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('status', 'D'), _negated=True), ('moderated_by__isnull', False)), ('status', 'D'), _connector='OR'), name='review_moderated_by_required', violation_error_message='Необходимо указать модератора'),
        ),
    ]
