# Generated by Django 6.0.4 on 2026-05-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_remove_review_review_published_at_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('A', 'Активно'), ('M', 'Перенесено'), ('CA', 'Отменено'), ('CL', 'Завершено'), ('P', 'В обработке')], default='A', max_length=2, verbose_name='Статус бронирования'),
        ),
    ]
